name: .NET CI

on:
  pull_request:
    branches: [ '*' ] 
  push:
    branches: [ 'main' ]  

jobs:
  build:
    runs-on: windows-latest  
    
    steps:
      - uses: actions/checkout@v4  

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  

      - name: Restore dependencies
        run: dotnet restore InnoClinic.AuthorizationAPI/InnoClinic.AuthorizationAPI.sln

      - name: Build
        run: dotnet build InnoClinic.AuthorizationAPI/InnoClinic.AuthorizationAPI.sln --configuration Release --no-restore